php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm, hhvm-nightly]

before_install:
  - echo 'hhvm.libxml.ext_entity_whitelist = file' > travis.hhvm.ini

install:
  - COMPOSER_ROOT_VERSION=dev-master composer install --prefer-source

env:
  global:
  -secure: qu/5u2aHH1gXdlTISscN/AaPTYF9iyczIZ8u2vOULf3VouSIJB4swxUfszIdIDfyhzokxn0z5RkoopYcIgYKlu9m29V7xbRObrUrZWalJzaCuMf5LpEyOsV1VaEhZVSl25V9mcbGJrcw2f6hItzuzu3rXnyQiL07cBoTy4XWrHc=
script:
   - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" -o "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then hhvm -c travis.hhvm.ini bin/phpspec run; else bin/phpspec run; fi;'
   - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "hhvm" -o "$TRAVIS_PHP_VERSION" = "hhvm-nightly" ]; then hhvm -c travis.hhvm.ini ./vendor/bin/behat --format=pretty; else ./vendor/bin/behat --format=pretty; fi;'
